# Deploy your Hyas site to GitHub Pages

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Hugo Extended
        run: |
          HUGO_VERSION=0.113.0
          HUGO_DOWNLOAD_URL=https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget ${HUGO_DOWNLOAD_URL}
          tar xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin

      - name: Check Hugo version
        run: hugo version

      - name: Install dependencies
        run: npm install

      - name: Check for linting errors
        run: ./node_modules/.bin/eslint --fix .

      - name: Build production website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
